#Details for each config setting can be found on the plugin's spigot page: https://www.spigotmc.org/resources/http-requests.101253/
PrintRequestsToConsole: false
AllowRequest: true
AllowPost: true
AllowGet: true

RequestTimeoutDuration: 10000

AllowChatSender: true
AllowCommandBlockSender: true
AllowConsoleSender: true

UseWhitelist: false
Whitelist: www.example.com

UseBlacklist: false
Blacklist: www.example.com

UseGlobalCooldown: false
GlobalCooldownMs: 500

UseUrlSpecificCooldown: true
UrlSpecificCooldown: 500

AllowReload: true