#Details for each config setting can be found on the plugin's spigot page: https://www.spigotmc.org/resources/http-requests.101253/

PrintRequestsToConsole: false
SendResponseCodeToPlayer: true
SendResponseBodyToPlayer: false

AllowRequest: true
AllowPost: true
AllowGet: true

RequestTimeoutDuration: 10000

AllowChatSender: true
AllowCommandBlockSender: true
AllowCommandBlockMinecartSender: true
AllowConsoleSender: true
AllowOtherSenders: false

UseWhitelist: false
UseBlacklist: false

UseGlobalCooldown: false
GlobalCooldownMs: 500

UseUrlSpecificCooldown: true
UrlSpecificCooldown: 500

MaxQueueSize: -1

SpaceCharacter: -#-

AllowReload: true
AllowWhitelistReload: true
AllowBlacklistReload: true

#--------------RESPONSE HANDLING--------------#
#The bellow config options can be dangerous to use if not configured properly
AllowResponseProcessing: false

UseResponseWhitelist: true
UseResponseBlacklist: false

AllowResponseWhitelistReload: true
AllowResponseBlacklistReload: true

AllowScriptReload: true