name: HttpRequests
version: '${project.version}'
main: me.dnamaster10.httprequests.HttpRequests
api-version: 1.13
authors: [ DNAmaster10 ]
description: A plugin that allows the server to send http GET and POST requests to a remote web server through a command block.
commands:
  httpSend:
    description: Used to send http requests to an external web server
    usage: /httpSend
  httpReload:
    description: Reloads plugin configuration
    usage: /httpReload
  httpReloadWhitelist:
    description: Reloads the whitelist
    usage: /httpReloadWhitelist
  httpReloadBlacklist:
    description: Reloads the blacklist
    usage: /httpReloadBlacklist
  httpReloadResponseWhitelist:
    description: Reloads the response processing whitelist
    usage: /httpReloadResponseWhitelist
  httpReloadResponseBlacklist:
    description: Reloads the response processing blacklist
    usage: /httpReloadResponseBlacklist
  httpReloadScript:
    description: Reloads the response processing javascript file
    usage: /httpReloadScript
